#!/bin/sh
#
#  signing-milter - debian/postinst
#  Copyright (C) 2010,2011  Andreas Schulze
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; only version 2 of the License is applicable.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  Authors:
#    Andreas Schulze <signing-milter at andreasschulze.de>
#
#

set -e

case "$1" in
    configure)
        . /usr/share/dv-baseconfig/account-management.sh

        _dv_check_or_create_group signing-milter 30053
        _dv_check_or_create_user signing-milter 30053 30053 'Signatur-Milter' /etc/signing-milter

        echo " - setzte Rechte fuer /etc/signing-milter"
        chgrp --changes signing-milter /etc/signing-milter/
        chmod --changes 0750 /etc/signing-milter/

        if [ ! -L /etc/service/signing-milter ]; then
            echo " - richte signing-milter ein ( starte aber noch nicht )"
            touch /var/lib/supervise/signing-milter/down
            ln -s ../../var/lib/supervise/signing-milter /etc/service/
        else
            echo " - starte signing-milter neu"
            svc -t /var/lib/supervise/signing-milter || :
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
