#!/bin/sh
#
#  signing-milter - statistics logging trigger
#  Copyright (C) 2024  Stefan Meinecke
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; only version 2 of the License is applicable.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -e

if [ -f /etc/default/signing-milter ]; then
    # shellcheck source=/dev/null
    . /etc/default/signing-milter
fi

MODE="$1"

case "${MODE}" in
    hourly)
        if [ "${DISABLE_HOURLY_STATISTICS_LOGGING}" != "yes" ]; then
            systemctl kill --signal=SIGALRM signing-milter.service
        fi
        ;;
    daily)
        if [ "${DISABLE_DAILY_STATISTICS_LOGGING}" != "yes" ] && [ "${DISABLE_HOURLY_STATISTICS_LOGGING}" = "yes" ]; then
            systemctl kill --signal=SIGALRM signing-milter.service
        fi
        ;;
    *)
        echo "Usage: $0 {hourly|daily}" >&2
        exit 1
        ;;
esac
