name: Build package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-debs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os-version: ["debian:buster", "debian:bullseye", "debian:bookworm", "ubuntu:noble", "ubuntu:jammy", "ubuntu:focal"]
        arch: ["amd64", "arm64"]
    steps:
      - uses: actions/checkout@v2
      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: "${{ matrix.os-version }}"
          host-arch: "${{ matrix.arch }}"
          extra-build-deps: devscripts git dpkg-cross
          before-build-hook: "dch --local ~${os_version##*:} 'GitHub build for ${{ matrix.os-version }}'"
          buildpackage-opts: --build=binary --no-sign -d
      - name: Upload deb files
        uses: actions/upload-artifact@v4
        with:
          name: "packages-${{ matrix.os-version }}-${{ matrix.arch }}"
          path: ./debian/artifacts/*

  merge-artefacts:
    runs-on: ubuntu-latest
    needs: build-debs
    steps:
      - name: debian-packages
        uses: actions/upload-artifact/merge@v4

  add_release:
    name: Add package to release
    needs: merge-artefacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: merged-artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./*.deb

  add_repo:
    runs-on: ubuntu-latest
    needs: build-debs
    strategy:
      max-parallel: 1
      matrix:
        os-version: ["buster", "bullseye", "bookworm", "noble", "jammy", "focal"]
        arch: ["amd64", "arm64"]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: "packages-${{ matrix.os-version }}-${{ matrix.arch }}"
      - name: Add ${{ matrix.arch }}/${{ matrix.os-version }} release
        uses: smeinecke/apt-repo-action@v2.1.4
        with:
          github_token: ${{ github.token }}
          repo_supported_arch: |
            amd64
            arm64
          repo_supported_version: |
            stretch
            buster
            bullseye
            bookworm
            noble
            jammy
            focal
          file: |
            *~${{ matrix.os-version }}*.deb
          file_target_version: ${{ matrix.os-version }}
          private_key: ${{ secrets.APT_SIGNING_KEY }}
          key_passphrase: ""
